AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10

Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.get
      Runtime: nodejs14.x
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /envios/pendientes
            Method: get
  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.put
      Runtime: nodejs14.x
      Events:
        PutRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /envios/{idEnvio}/entregado
            Method: put
  PostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: app.post
      Runtime: nodejs14.x
      Events:
        PostRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /envios
            Method: post
